"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Key = void 0;
var Key;
(function (Key) {
    Key[Key["Q"] = 0] = "Q";
    Key[Key["W"] = 1] = "W";
    Key[Key["E"] = 2] = "E";
    Key[Key["R"] = 3] = "R";
    Key[Key["T"] = 4] = "T";
    Key[Key["Y"] = 5] = "Y";
    Key[Key["U"] = 6] = "U";
    Key[Key["I"] = 7] = "I";
    Key[Key["O"] = 8] = "O";
    Key[Key["P"] = 9] = "P";
    Key[Key["A"] = 10] = "A";
    Key[Key["S"] = 11] = "S";
    Key[Key["D"] = 12] = "D";
    Key[Key["F"] = 13] = "F";
    Key[Key["G"] = 14] = "G";
    Key[Key["H"] = 15] = "H";
    Key[Key["J"] = 16] = "J";
    Key[Key["K"] = 17] = "K";
    Key[Key["L"] = 18] = "L";
    Key[Key["Z"] = 19] = "Z";
    Key[Key["X"] = 20] = "X";
    Key[Key["C"] = 21] = "C";
    Key[Key["V"] = 22] = "V";
    Key[Key["B"] = 23] = "B";
    Key[Key["N"] = 24] = "N";
    Key[Key["M"] = 25] = "M";
    Key[Key["CTRL"] = 26] = "CTRL";
    Key[Key["SHIFT"] = 27] = "SHIFT";
    Key[Key["SPACE"] = 28] = "SPACE";
})(Key = exports.Key || (exports.Key = {}));
